# Generated by Django 3.0.1 on 2020-04-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_no',
            name='emaill',
            field=models.EmailField(default='test@gmail.com', max_length=254),
        ),
    ]
