# Generated by Django 3.0.1 on 2020-04-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formm', '0002_student_no_emaill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_no',
            old_name='emaill',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='student_no',
            name='idd',
        ),
        migrations.AlterField(
            model_name='student_no',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
