# Generated by Django 3.0.1 on 2020-07-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formnew', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
